/**
 * @category Character
 * @module Job
 */

export class Job {
    id: Job.ID = Job.ID.beginner;
    grade: Job.Grade = Job.Grade.Beginner;
}

export namespace Job {
    export enum Grade {
        Beginner = 0,
        First = 1,
        Second = 2,
        Third = 3,
        Fourth = 4,
    }
    export enum ID {
        beginner = 0,
        swordsman = 100,
        fighter = 110,
        crusader = 111,
        hero = 112,
        page = 120,
        white_knight = 121,
        paladin = 122,
        spearman = 130,
        dragon_knight = 131,
        dark_knight = 132,
        magician = 200,
        wizard_FP = 210,
        mage_FP = 211,
        archmage_FP = 212,
        wizard_IL = 220,
        mage_IL = 221,
        archmage_IL = 222,
        cleric = 230,
        priest = 231,
        bishop = 232,
        archer = 300,
        hunter = 310,
        ranger = 311,
        bowmaster = 312,
        crossbowman = 320,
        sniper = 321,
        marksman = 322,
        rogue = 400,
        assassin = 410,
        hermit = 411,
        nightlord = 412,
        bandit = 420,
        chief_bandit = 421,
        shadower = 422,
        pirate = 500,
        brawler = 510,
        marauder = 511,
        buccaneer = 512,
        gunslinger = 520,
        outlaw = 521,
        corsair = 522,
        noblesse = 1000,
        dawn_warrior = 1100,
        blaze_wizard = 1200,
        wind_archer = 1300,
        night_walker = 1400,
        thunder_breaker = 1500,
        aran = 2000,
    }
    export const Name = {
        [Job.ID.beginner] : "初心者",
        [Job.ID.swordsman] : "劍士",
        [Job.ID.fighter] : "狂戰士",
        [Job.ID.crusader] : "十字軍",
        [Job.ID.hero] : "英雄",
        [Job.ID.page] : "見習騎兵",
        [Job.ID.white_knight] : "騎士",
        [Job.ID.paladin] : "聖騎士",
        [Job.ID.spearman] : "槍騎兵",
        [Job.ID.dragon_knight] : "龍騎士",
        [Job.ID.dark_knight] : "黑騎士",
        [Job.ID.magician] : "法師",
        [Job.ID.wizard_FP] : "巫師(火毒)",
        [Job.ID.mage_FP] : "魔導士(火毒)",
        [Job.ID.archmage_FP] : "火毒大魔導士",
        [Job.ID.wizard_IL] : "巫師(冰雷)",
        [Job.ID.mage_IL] : "魔導士(冰雷)",
        [Job.ID.archmage_IL] : "冰雷大魔導士",
        [Job.ID.cleric] : "僧侶",
        [Job.ID.priest] : "祭司",
        [Job.ID.bishop] : "主教",
        [Job.ID.archer] : "弓箭手",
        [Job.ID.hunter] : "獵人",
        [Job.ID.ranger] : "遊俠",
        [Job.ID.bowmaster] : "箭神",
        [Job.ID.crossbowman] : "弩弓手",
        [Job.ID.sniper] : "狙擊手",
        [Job.ID.marksman] : "神射手",
        [Job.ID.rogue] : "盜賊",
        [Job.ID.assassin] : "刺客",
        [Job.ID.hermit] : "暗殺",
        [Job.ID.nightlord] : "夜使者",
        [Job.ID.bandit] : "俠盜",
        [Job.ID.chief_bandit] : "神偷",
        [Job.ID.shadower] : "暗影神偷",
        [Job.ID.pirate] : "海盜",
        [Job.ID.brawler] : "打手",
        [Job.ID.marauder] : "格鬥手",
        [Job.ID.buccaneer] : "拳霸",
        [Job.ID.gunslinger] : "槍手",
        [Job.ID.outlaw] : "神槍手",
        [Job.ID.corsair] : "槍神",
        [Job.ID.noblesse] : "皇家騎士團",
        [Job.ID.dawn_warrior] : "聖魂劍士",
        [Job.ID.blaze_wizard] : "烈焰巫師",
        [Job.ID.wind_archer] : "破風使者",
        [Job.ID.night_walker] : "暗夜行者",
        [Job.ID.thunder_breaker] : "閃雷悍將",
        [Job.ID.aran] : "狂狼戰士",
    }
}