const AudioData: {[key: string]: string}= {
    "BtMouseClick": "UI/BtMouseClick.mp3",
    "BtMouseOver": "UI/BtMouseOver.mp3",
    "CharSelect": "UI/CharSelect.mp3",
    "DlgNotice": "UI/DlgNotice.mp3",
    "MenuDown": "UI/MenuDown.mp3",
    "MenuUp": "UI/MenuUp.mp3",
    "RaceSelect": "UI/RaceSelect.mp3",
    "ScrollUp": "UI/ScrollUp.mp3",
    "SelectMap": "UI/SelectMap.mp3",
    "Tab": "UI/Tab.mp3",
    "WorldSelect": "UI/WorldSelect.mp3",
    "DragStart": "UI/DragStart.mp3",
    "DragEnd": "UI/DragEnd.mp3",
    "WorldmapOpen": "UI/WorldmapOpen.mp3",
    "WorldmapClose": "UI/WorldmapClose.mp3",
    "GameIn": "Game/GameIn.mp3",
    "Jump": "Game/Jump.mp3",
    "DropItem": "Game/DropItem.mp3",
    "PickUpItem": "Game/PickUpItem.mp3",
    "Portal": "Game/Portal.mp3",
    "LevelUp": "Game/LevelUp.mp3",
    "Tombstone": "Game/Tombstone.mp3",
}

export default AudioData;