const AudioData: {[key: string]: string}= {
    "BtMouseClick": "UI.img/BtMouseClick.mp3",
    "BtMouseOver": "UI.img/BtMouseOver.mp3",
    "CharSelect": "UI.img/CharSelect.mp3",
    "DlgNotice": "UI.img/DlgNotice.mp3",
    "MenuDown": "UI.img/MenuDown.mp3",
    "MenuUp": "UI.img/MenuUp.mp3",
    "RaceSelect": "UI.img/RaceSelect.mp3",
    "ScrollUp": "UI.img/ScrollUp.mp3",
    "SelectMap": "UI.img/SelectMap.mp3",
    "Tab": "UI.img/Tab.mp3",
    "WorldSelect": "UI.img/WorldSelect.mp3",
    "DragStart": "UI.img/DragStart.mp3",
    "DragEnd": "UI.img/DragEnd.mp3",
    "WorldmapOpen": "UI.img/WorldmapOpen.mp3",
    "WorldmapClose": "UI.img/WorldmapClose.mp3",
    "GameIn": "Game.img/GameIn.mp3",
    "Jump": "Game.img/Jump.mp3",
    "DropItem": "Game.img/DropItem.mp3",
    "PickUpItem": "Game.img/PickUpItem.mp3",
    "Portal": "Game.img/Portal.mp3",
    "LevelUp": "Game.img/LevelUp.mp3",
    "Tombstone": "Game.img/Tombstone.mp3",
}

export default AudioData;