name: Build & Deploy documents
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Npm install
        run: npm install

      - name: Build doc/
        run: npm run doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs