# This is a basic workflow to help you get started with Actions

name: Docs
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Npm install
        run: npm install
      - name: Build doc/
        run: npm run doc
      - name: Accept GitHub
        run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs